# Generated by Django 5.2.4 on 2025-08-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('idTipoAnuncio', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('is_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TipoAnuncio',
                'verbose_name_plural': 'TipoAnuncios',
                'ordering': ['idTipoAnuncio'],
            },
        ),
        migrations.AlterModelOptions(
            name='anuncios',
            options={'ordering': ['id'], 'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AddField(
            model_name='anuncios',
            name='idTipoAnuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketsadmin.tipoanuncio'),
        ),
    ]
