# Generated by Django 5.2.4 on 2025-08-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsadmin', '0002_tipoanuncio_alter_anuncios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoanuncio',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
