# Generated by Django 5.2.4 on 2025-08-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apodo',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
