# Generated by Django 5.2.4 on 2025-08-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_apodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crear_ticket',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
