# Generated by Django 5.2.4 on 2025-08-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_crear_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='crear_ticket',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
