# Generated by Django 5.2.4 on 2025-08-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_crear_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='crear_ticket',
            new_name='is_admin',
        ),
    ]
