# Generated by Django 5.2.4 on 2025-08-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_crear_ticket_usuario_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crea_ticket',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
