# Generated by Django 5.2.4 on 2025-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_crea_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
