# Generated by Django 5.2.4 on 2025-07-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_areas_options_alter_cargos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='is_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargos',
            name='is_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nivel',
            name='is_activo',
            field=models.BooleanField(default=True),
        ),
    ]
