# Generated by Django 5.2.4 on 2025-07-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_areas_is_activo_cargos_is_activo_nivel_is_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
    ]
