# Generated by Django 5.2.4 on 2025-08-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_nivel_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'ordering': ['id'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
