# Generated by Django 5.2.4 on 2025-08-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_cargos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajesTicket',
            fields=[
                ('id_mensaje', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mensaje', models.TextField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_visto', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('is_cerrado', models.BooleanField(default=True)),
                ('is_activo', models.BooleanField(default=True)),
                ('id_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Mensajes',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['id_mensaje'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaMensajeTicket',
            fields=[
                ('id_respuesta', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_activo', models.BooleanField(default=True)),
                ('id_mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.mensajesticket')),
            ],
            options={
                'verbose_name': 'Respuesta a Mensaje',
                'verbose_name_plural': 'Respuestas a Mensajes',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
