# Generated by Django 5.2.4 on 2025-08-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_mensajesticket_respuestamensajeticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_cargo',
        ),
    ]
