# Generated by Django 5.2.4 on 2025-08-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_id_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_area',
        ),
    ]
