# Generated by Django 5.2.4 on 2025-08-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.areas'),
        ),
    ]
