# Generated by Django 5.2.4 on 2025-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
